fix(compilation): 'uint32_t' has not been declared with newer GCC (#3224)
In file included from /builddir/build/BUILD/edgetx-2.8.1/radio/src/gui/colorlcd/str_functions.cpp:25:
/builddir/build/BUILD/edgetx-2.8.1/radio/src/gui/colorlcd/str_functions.h:30:42: error: 'uint32_t' has not been declared
   30 | extern std::string wrap(std::string str, uint32_t width);
      |                                          ^~~~~~~~

Fixes #3222.