feat: Add support for Japanese voice language 🇯🇵 (#3261)
* Created tts_jp.cpp and added "TR_VOICE_JAPANESE" to the *.h file.

* Commented out once because the build did not work

* fix: Define `JP` as a TTS language,
- Fixes the undefined reference to `jpLanguagePack` error
- put things in alphabetical order as the comment suggests it should be

* chore: Add `JP` to Companion voice language list

---------

Co-authored-by: Peter Feerick <peter.feerick@gmail.com>